# Generated by Django 2.1 on 2019-03-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfile', '0002_auto_20190307_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='description',
        ),
        migrations.RemoveField(
            model_name='share',
            name='file',
        ),
    ]
